[package]
name = "ENSResolver"
version = "1.0.0"
authors = []

[addresses]
std =  "0x1"
sender = "0xAA6B468E23915071B7A87AD9FC1990F94FDD2780"

[dev-addresses]

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives", subdir = "initia_stdlib", rev = "main" }

[dev-dependencies]
